services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=091204
      - MYSQL_DATABASE=weather_db
      - MYSQL_USER=weather_user
      - MYSQL_PASSWORD=motdepasse_weather
    volumes:
      - mysql-data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - weather-network
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    ports:
      - "5000:5000"
    networks:
      - weather-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=weather_user
      - MYSQL_PASSWORD=motdepasse_weather
      - MYSQL_DATABASE=weather_db

networks:
  weather-network:
    driver: bridge

volumes:
  mysql-data: